//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndividualTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<System.Guid> ContactId { get; set; }
        public Nullable<System.Guid> TypeId { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
